import { expect, test } from "@playwright/test";

const feed = { post_id: 1, content: "Figma 기준 커뮤니티 피드", nickname: "PULSE 사용자", created_at: new Date().toISOString(), like_count: 3, comment_count: 1, view_count: 12, image_url: null, comment: [] };
async function mockApi(page) {
  await page.route("http://*/api/**", async (route) => { const url = new URL(route.request().url()); if (url.pathname === "/api/csrf") return route.fulfill({ status: 200, headers: { "Set-Cookie": "XSRF-TOKEN=test; Path=/" } }); if (url.pathname === "/api/posts") return route.fulfill({ json: { data: { content: [feed] } } }); if (url.pathname === "/api/posts/1") return route.fulfill({ json: { data: feed } }); return route.fulfill({ json: { data: {} } }); });
}
test("피드 1920 레이아웃과 생성 모달", async ({ page }) => { await mockApi(page); await page.goto("/pages/posts/posts.html"); await expect(page.getByText("Figma 기준 커뮤니티 피드")).toBeVisible(); const content = await page.locator("main.page").boundingBox(); const lnb = await page.locator("[data-app-lnb]").boundingBox(); expect(content.width).toBeCloseTo(480, 0); expect(content.x + content.width / 2).toBeCloseTo(960, 0); expect(content.x - (lnb.x + lnb.width)).toBeCloseTo(40, 0); await page.getByRole("button", { name: "피드 게시하기" }).click(); await expect(page.getByRole("dialog")).toBeVisible(); await expect(page.locator("body")).toHaveClass(/is-modal-open/); await page.keyboard.press("Escape"); await expect(page.getByRole("dialog")).toBeHidden(); });
test("로그인은 화면을 정확히 절반으로 나눈다", async ({ page }) => { await page.goto("/pages/login/login.html"); const art = await page.locator(".auth-artwork").boundingBox(); const main = await page.locator(".auth-main").boundingBox(); expect(art.width).toBeCloseTo(960, 0); expect(main.width).toBeCloseTo(960, 0); await expect(page.locator(".auth-panel")).toHaveCSS("width", "343px"); });
test("북마크는 같은 브라우저에서 유지되고 해제된다", async ({ page }) => { await mockApi(page); await page.goto("/pages/posts/posts.html"); await page.getByRole("button", { name: "북마크" }).click(); await page.goto("/pages/bookmarks/bookmarks.html"); await expect(page.getByText("Figma 기준 커뮤니티 피드")).toBeVisible(); await page.getByRole("button", { name: "북마크" }).click(); await expect(page.getByText("아직 저장한 피드가 없어요")).toBeVisible(); });
test("상세 댓글 입력과 옵션 메뉴", async ({ page }) => { await mockApi(page); await page.goto("/pages/post-detail/post-detail.html?postId=1"); await expect(page.getByText("Figma 기준 커뮤니티 피드")).toBeVisible(); const input = page.getByLabel("댓글 작성"); await input.fill("댓글입니다"); await expect(page.getByRole("button", { name: "댓글 등록" })).toBeEnabled(); await page.getByRole("button", { name: "피드 옵션" }).click(); await expect(page.getByRole("menu")).toBeVisible(); });
